# Generated by Django 4.1.6 on 2023-02-15 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_telegramuser_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='first_name',
        ),
    ]
